{
 "title": "RocketMQ",
 "description": "Monitor RocketMQ by Prometheus, use RocketMQ Exporter",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Broker TPS/QPS",
   "type": "timeseries",
   "gridPos": { "h": 13, "w": 16, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "rocketmq_broker_tps",
     "legendFormat": "Broker-TPS-{{broker}}-{{brokerIP}}"
    },
    {
     "expr": "rocketmq_broker_qps",
     "legendFormat": "Broker-QPS-{{broker}}-{{brokerIP}}"
    }
   ]
  },
  {
   "title": "磁盘使用率",
   "type": "gauge",
   "gridPos": { "h": 13, "w": 8, "x": 16, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(rocketmq_brokeruntime_commitlog_disk_ratio) by (brokerIP) * 100",
     "legendFormat": "{{brokerIP}}"
    }
   ]
  },
  {
   "title": "消息积压",
   "type": "table",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 13 },
   "targets": [
    {
     "expr": "sum(rocketmq_producer_offset) by (topic) - on(topic)  group_right  sum(rocketmq_consumer_offset) by (group,topic) and (sum(rocketmq_producer_offset) by (topic) - on(topic)  group_right  sum(rocketmq_consumer_offset) by (group,topic) > 0)"
    }
   ]
  },
  {
   "title": "消息积压",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 12, "x": 12, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(rocketmq_producer_offset) by (topic) - on(topic)  group_right  sum(rocketmq_consumer_offset) by (group,topic) and (sum(rocketmq_producer_offset) by (topic) - on(topic)  group_right  sum(rocketmq_consumer_offset) by (group,topic) > 0)"
    }
   ]
  },
  {
   "title": "生产者TPS",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(rocketmq_producer_tps) by (topic)",
     "legendFormat": "生产者-TPS-{{topic}}"
    }
   ]
  },
  {
   "title": "消费者TPS",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(rocketmq_consumer_tps) by (topic)",
     "legendFormat": "消费者-TPS-{{topic}}"
    }
   ]
  },
  {
   "title": "生产者每秒消息大小",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 36 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(rocketmq_producer_message_size) by (topic)",
     "legendFormat": "生产者-{{topic}}"
    }
   ]
  },
  {
   "title": "消费者每秒消息大小",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 36 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(rocketmq_consumer_message_size) by (topic)",
     "legendFormat": "消费者-{{topic}}"
    }
   ]
  },
  {
   "title": "生产消息进度-Offset",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 45 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(rocketmq_producer_offset) by (broker,topic)",
     "legendFormat": "生产者-{{topic}}-{{broker}}"
    }
   ]
  },
  {
   "title": "消费消息进度-Offset",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 45 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(rocketmq_consumer_offset) by (broker,topic)",
     "legendFormat": "消费者-{{topic}}-{{broker}}"
    }
   ]
  },
  {
   "title": "消费组的消费延时时间",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 56 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "sort_desc(sum(rocketmq_group_get_latency_by_storetime) by (broker,group,topic)) and (sum(rocketmq_group_get_latency_by_storetime) by (broker,group,topic) > 0)"
    }
   ]
  }
 ]
}